### PR TITLE
Playground / nodejs dht libp2p example

### PR DESCRIPTION
**Pull request by Arxcis**

### CODE REVIEW

**Comment by Arxcis** [comment]
> Haha setting up your own p2p network :P ?

I was just thinking. If we are going to have two agents talking to each other, they could talk to each other in two ways:
- Agent -> Server (mediator) <- Agent
- Agent -> <- Agent 

libp2p enables the second setup. It is very tempting to experiment with it at least.

**Comment by Arxcis** [comment]
> Haha setting up your own p2p network :P ?

DIDComm is transport-agnostic, so I am considering which transports to use. This PR explores one of them.

**DIDComm transports considered**
- HTTP REST
- QR code
- Copy/paste
- Unix stdin / stdout
- File
- libp2p + Kademlia (explored in this PR)
- WebRTC
- email IMAP
- Text message (Discord, Signal, Slack, SMS, etc)

**Comment by Arxcis** [comment]
> Haha setting up your own p2p network :P ?

As with **DIDComm**, **libp2p** is transport-agnostic, which makes **libp2p** a very good fit for the "did-stack".

**Comment by vongohren** [comment]
Sounds good, just remember to not become to technology h***y :P
It is easy to forget to solve the problem and take agnostic choices on what make sense to get to some kind of goal.

**Comment by Arxcis** [comment]
> Sounds good, just remember to not become to technology h***y :P
> It is easy to forget to solve the problem and take agnostic choices on what make sense to get to some kind of goal.

That makes sense, if you actually **know** what the problem you are trying to solve is, which I don't quite know yet, so I am exploring.

**Comment by vongohren** [comment]
> > Sounds good, just remember to not become to technology h***y :P
> > It is easy to forget to solve the problem and take agnostic choices on what make sense to get to some kind of goal.
> 
> That makes sense, if you actually **know** what the problem you are trying to solve is, which I don't quite know yet, so I am exploring.

Well adding a new transport technology into the mix, does seem to me a bit overkill. But explore away and it is probably good learning. If you nail didcom with rust, you are transport agnostic.

**Pull request merged**
